### ISSUE TITLE
grep: invalid option -- P

### ISSUE THREAD

**Issue by albert-ying** [BeyondMagic/nincat#11]
On MacOS, every time I run the command, it gives an error message like this (while still working, just a little bit annoying to see warning).

<img width="920" alt="image" src="https://user-images.githubusercontent.com/59846322/150023104-7fff2688-8d22-4d1b-9a44-a8069fb4142e.png">

**Comment by BeyondMagic** [comment]
I think I already know the problem, but could you run `nincat --random --center` to see if it centers in the terminal?

**Comment by albert-ying** [comment]
Thank you! It does.

<img width="1682" alt="image" src="https://user-images.githubusercontent.com/59846322/150155846-e237ae00-2b35-48d1-9181-64aa77b9a0a8.png">

**Comment by BeyondMagic** [comment]
Fixed on 0e3268b8333847dbc240604f0bd30e6577d019d2, please update the repository you have with `git pull` and `make` afterwards.
