### ISSUE TITLE
ANSI characters displayed as strings

### ISSUE THREAD

**Issue by Dam-Buty** [BeyondMagic/nincat#9]
- `bash 5.1.12`
- `terminator 2.1.1`:
- `xterm-256color`

## Steps to Reproduce the Problem

Run `nincat --random --center` in terminal or in .bashrc . ANSI special characters are displayed as string such as `\033[1m`.

## Log

![image](https://user-images.githubusercontent.com/1461760/148453162-49c650bc-1b15-4391-a178-482386bb8f91.png)

```bash
> printf "C: $(tput cols)\nR: $(tput lines)\n"
C: 84
R: 26
```

**Comment by BeyondMagic** [comment]
Hey, thanks for putting this here.

I don't know if you're cloning from source, but if you are, on the nincat folder just update it with:

```bash
$ git pull
$ make
$ nincat --random --center
```

Edit: sorry, forgot some extra commands ^

--------

Actually, I believe this to be some specialty of bash -- I can't replace the echo command with `-e` option as it would break dash, but I'll figure it out eventually.

![new_desktop](https://user-images.githubusercontent.com/51831435/148457001-9ee4ecfa-7409-4a5b-b4b1-21fae4f53dde.png)

**Comment by BeyondMagic** [comment]
Hi!

As a workaround (for now) you could install `dash` (recommended) or `zsh` on your system to run nincat

```bash
$ zsh $(which nincat) --random --center
```

**Comment by Dam-Buty** [comment]
Actually i've been playing around with the option that removes the need for `-e` , and it works when i use echo manually, but not with nincat so there might still be an underlying problem : 

![image](https://user-images.githubusercontent.com/1461760/148502291-185e72e1-e161-49f4-9047-b5da74ce47b7.png)

**Comment by BeyondMagic** [comment]
Thanks for this update, because now we can make so that nincat uses a special condition for bash and runs `shopt -s xpg_echo` before it loads `echo` to load the art.

Though it is not the nicest solution but I can't see one better out of my head right now.
